FROM ghcr.io/openhd/bullseye-lite:v2.3

COPY .git /data/.git/
COPY flir8p1-gpl /data/flir8p1-gpl/
COPY package.sh /data/

RUN apt update --allow-releaseinfo-change

RUN apt -y install git

RUN apt -y install build-essential

RUN apt -y install ruby-dev

RUN apt -y install python3-pip

RUN gem install fpm

RUN pip install cloudsmith-cli

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh armhf raspbian bullseye docker
