FROM ghcr.io/openhd/2020-05-27-raspios-buster-lite-armhf:latest

COPY .git /data/.git/
COPY flir8p1-gpl /data/flir8p1-gpl/
COPY package.sh /data/

RUN apt update --allow-releaseinfo-change

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh armhf raspbian buster docker
